# Generated by Django 2.2.4 on 2020-11-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Python_BeltExam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='city',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='state',
        ),
    ]
